Add ipgen(1) manual page
iij/ipgen pull request #39
Opened 2024-02-29 05:08 UTC by hrs-allbsd

This patchset adds ipgen(1) manual page.  While it has only several examples and no detail about the command-line options at this moment, more additions will be made later.

The following changes are also included here:

- Add DESTDIR for staging in GNU Coding Standards.
- Define LOCALBASE and MANDIR.

These are adjustments for packaging in the FreeBSD Ports Collection.  Regarding DESTDIR, see also https://www.gnu.org/prep/standards/html_node/DESTDIR.html

2024-03-05 09:19 UTC, ozaki-r requested changes
Thank you for your contribution!

The changes look ok to me except for the following point.

Please update the `AUTHORS` section from:

```
AUTHORS
       The ipgen utility was designed and implemented by Ryota Ozaki <ryo@iij.ad.jp>.
```

to:

```
AUTHORS
       The ipgen utility was designed and implemented by Ryo Shimizu and is maintained by IIJ.
```

Regards.

2024-05-13 05:45 UTC, ozaki-r commented
We've decided to merge this PR regardless of the above issue. We think it is better to merge it and fix the issue in another PR than we will have been stuck on this PR for more time.

Anyway, thank you for the contribution!

2024-05-13 05:45 UTC, merged

2024-05-13 05:52 UTC, hrs-allbsd commented
> We've decided to merge this PR regardless of the above issue. We think it is better to merge it and fix the issue in another PR than we will have been stuck on this PR for more time.
> 
> Anyway, thank you for the contribution!

Sorry for not responding to it in a timely manner.  Some real-life issues in March and April kept me away from the keyboard and I forgot to reply.  Thank you for merging the changes.

2024-05-13 06:19 UTC, ozaki-r commented
No problem. I heard your severe situation a bit via saitoh-san. Take care of yourself.